version: '3'

services:
  # React
  frontend:
    build:
      context: https://github.com/waldbrandpraevention/frontend.git
    volumes:
      - frontend-build:/app/build

  # API
  backend:
    build:
      context: https://github.com/waldbrandpraevention/backend.git
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --root-path /api

  # Reverse Proxy
  nginx:
    image: nginx:latest
    ports:
      - 8080:8000
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend-build:/usr/share/nginx/html

  # Mail
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  frontend-build:
