version: '3'
name: Waldbrandpraevention

services:
  # React
  frontend:
    image: waldbrandpraevention/frontend
    ports:
      - 8080:80

  # API
  backend:
    image: waldbrandpraevention/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /api
    environment:
      - ADMIN_MAIL=admin@kiwa.tech 
      - ADMIN_PASSWORD=adminkiwa
      - ADMIN_ORGANIZATION=KIWA
      - DB_PATH=/api/data/testing.db
      - DB_BACKUP_PATH=/api/data/backuptest.db
      - DEMO_LONG=12.68895149
      - DEMO_LAT=52.07454738
      - GEOJSON_PATH=/api/data/zone_data.geojson
      - DEMO_DISTRICT=Landkreis Potsdam-Mittelmark
      - DOMAIN_API=domain.tld/api/
      - DRONE_FEEDBACK_PATH=/api/data/drone_feedback
      - EVENT_PATH=/api/data/events
      - ALARM_PATH=/api/data/alarms
      - SIMULATION_EVENT_CHANCE = '0.01'
      - SIMULATION_UPDATE_FREQUENCY = '600'
      - SIMULATION_DRONE_SPEED_MIN = '0.0001'
      - SIMULATION_DRONE_SPEED_MAX = '0.0002'
      # - SMTP_HOST=mail.domain.tld
      # - SMTP_USER=
      # - SMTP_PASSWORD=
      # - SMTP_PORT=25
      # - SMTP_SENDER=no-reply@domain.tld
    volumes:
      - kiwa-data:/api/data
      
  # Windserver
  wind:
    image: waldbrandpraevention/wind
    volumes:
      - wind-data:/api/json-data
      
volumes:
  kiwa-data:
  wind-data: