version: '3'
name: Waldbrandpraevention

services:
  # React
  frontend:
    image: waldbrandpraevention/frontend
    ports:
      - 8080:80

  # API
  backend:
    image: waldbrandpraevention/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /api
    environment:
      - ADMIN_MAIL=admin@kiwa.tech 
      - ADMIN_PASSWORD=adminkiwa
      - ADMIN_ORGANIZATION=KIWA
      - DB_PATH=/data/testing.db
      - DB_BACKUP_PATH=/data/backuptest.db
      - DEMO_LONG=12.68895149
      - DEMO_LAT=52.07454738
      - GEOJSON_PATH=/data/zone_data.geojson
      - DEMO_DISTRICT=Landkreis Potsdam-Mittelmark
      - DOMAIN_API=domain.tld/api/
      - DRONE_FEEDBACK_PATH=/data/drone_feedback
      - EVENT_PATH/data/events
      - ALARM_PATH=/data/alarms
      # - SMTP_HOST=mail.domain.tld
      # - SMTP_USER=
      # - SMTP_PASSWORD=
      # - SMTP_PORT=25
      # - SMTP_SENDER=no-reply@domain.tld
    volumes:
      - kiwa-data:/data