version: '3'

services:
  # React
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend-build:/app/build

  # API
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --root-path /api

  # Reverse Proxy
  nginx:
    image: nginx:latest
    ports:
      - 8080:8000
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend-build:/usr/share/nginx/html

volumes:
  frontend-build:
